/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:09:36 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@interface DOMNodeList

@property (readonly) unsigned length;
-(void)dealloc;
-(unsigned)length;
-(id)item:(unsigned)arg1 ;
-(void)finalize;
@end
