/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:09:36 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

//#import <WebCore/WebCore-Structs.h>
//#import <WebCore/DOMObject.h>
//#import <libobjc.A.dylib/DOMEventTarget.h>
#import "DOMNodeList.h"

@class NSString, DOMNodeList, /*DOMDocument, DOMNamedNodeMap, */DOMElement;

@interface DOMNode : NSObject// : DOMObject <DOMEventTarget>

@property (copy,readonly) NSString * nodeName;
@property (copy) NSString * nodeValue;
@property (readonly) unsigned short nodeType;
@property (readonly) DOMNode * parentNode;
@property (readonly) DOMNodeList * childNodes;
@property (readonly) DOMNode * firstChild;
@property (readonly) DOMNode * lastChild;
@property (readonly) DOMNode * previousSibling;
@property (readonly) DOMNode * nextSibling;
@property (copy,readonly) NSString * namespaceURI;
@property (copy) NSString * prefix;
@property (copy,readonly) NSString * localName;
@property (copy,readonly) NSString * baseURI;
@property (copy) NSString * textContent;
@property (readonly) DOMElement * parentElement;
@property (readonly) BOOL isContentEditable;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (copy,readonly) NSString * description;
@property (copy,readonly) NSString * debugDescription;
-(id)boundingBoxes;
-(id)borderRadii;
-(id)absoluteQuads;
-(double)textHeight;
-(id)findExplodedTextNodeAtPoint:(CGPoint)arg1 ;
-(id)rangeOfContainingParagraph;
-(BOOL)isSelectableBlock;
-(BOOL)containsOnlyInlineObjects;
-(id)textRects;
-(id)lineBoxRects;
-(id)lineBoxQuads;
-(id)hrefTarget;
-(CGRect)hrefFrame;
-(id)hrefTitle;
-(CGRect)boundingBoxUsingTransforms;
-(id)hrefLabel;
-(CGRect)boundingFrame;
-(id)hrefURL;
-(CGRect)boundingBox;
-(id)nextFocusNode;
-(id)previousFocusNode;
-(float)computedFontSize;
-(NSString *)description;
-(NSString *)nodeValue;
-(id)lookupNamespaceURI:(id)arg1 ;
-(void)addEventListener:(id)arg1 listener:(id)arg2 useCapture:(BOOL)arg3 ;
-(void)removeEventListener:(id)arg1 listener:(id)arg2 useCapture:(BOOL)arg3 ;
-(BOOL)dispatchEvent:(id)arg1 ;
-(void)addEventListener:(id)arg1 :(id)arg2 :(BOOL)arg3 ;
-(void)removeEventListener:(id)arg1 :(id)arg2 :(BOOL)arg3 ;
-(void)setNodeValue:(NSString *)arg1 ;
-(NSString *)baseURI;
-(id)insertBefore:(id)arg1 :(id)arg2 ;
-(id)replaceChild:(id)arg1 :(id)arg2 ;
-(BOOL)isSupported:(id)arg1 version:(id)arg2 ;
-(BOOL)isSupported:(id)arg1 :(id)arg2 ;
-(id)lookupPrefix:(id)arg1 ;
-(BOOL)isDefaultNamespace:(id)arg1 ;
-(unsigned short)compareDocumentPosition:(id)arg1 ;
-(void)dealloc;
-(DOMNode *)lastChild;
-(DOMNode *)firstChild;
-(BOOL)isContentEditable;
-(DOMNode *)parentNode;
-(DOMNode *)previousSibling;
-(id)removeChild:(id)arg1 ;
-(BOOL)isSameNode:(id)arg1 ;
-(void)inspect;
-(unsigned short)nodeType;
-(DOMElement *)parentElement;
-(DOMNode *)nextSibling;
-(void)setPrefix:(NSString *)arg1 ;
-(NSString *)prefix;
-(BOOL)contains:(id)arg1 ;
-(NSString *)localName;
-(id)replaceChild:(id)arg1 oldChild:(id)arg2 ;
-(id)appendChild:(id)arg1 ;
-(id)insertBefore:(id)arg1 refChild:(id)arg2 ;
-(BOOL)isEqualNode:(id)arg1 ;
-(id)cloneNode:(BOOL)arg1 ;
-(BOOL)hasAttributes;
-(void)normalize;
-(BOOL)hasChildNodes;
-(NSString *)namespaceURI;
-(NSString *)textContent;
-(NSString *)nodeName;
-(void)setTextContent:(NSString *)arg1 ;
-(void)finalize;
@end
